dist: bionic

language: java
jdk:
    - openjdk11

install:
    - sudo add-apt-repository -y ppa:mhier/libboost-latest
    - sudo apt-get -q update
    - sudo apt-get -y install libboost1.73-dev

addons:
    artifacts:
        paths:
            - dist/*.jar
    sonarcloud:
        organization: cril
        token:
            secure: $SONAR_TOKEN

jobs:
    include:
        - stage: test
          script: ./gradlew clean test jacocoTestReport
        - stage: package
          script: ./gradlew jars
        - stage: sonar
          script: sonar-scanner
