dist: bionic
language: java
jdk:
    - openjdk11
script:
    - sudo add-apt-repository -y ppa:mhier/libboost-latest
    - sudo apt-get -q update
    - sudo apt-get -y install libboost1.70-dev
    - git submodule update --remote --init --recursive
    - ./gradlew clean test
