dist: bionic

language: java
jdk:
    - openjdk11

install:
    - sudo add-apt-repository -y ppa:mhier/libboost-latest
    - sudo apt-get -q update
    - sudo apt-get -y install libboost1.73-dev

addons:
    sonarcloud:
        organization: "cril"
        token:
            secure: "d39t6+53P/CgMkWGab6c4IyNgqJinSJ+zmomgl3/xuhO7B+CXq/IoWq6SAFLue1Nv+Q700p7o7uNjfy36y8Ym6YcLZ/EljAodPwGGD0agS97FygW6RxRWcDbgKHCgju7adKFyaZoNK/Q6UKvRxbpOZnXtdq2/ajFWY4yR6Q1nfl//z3WSUSAx0uJC1SjkZ9DnaOS46v3KxquUe0b0RZclbkmMn026lhhXUwskB6azEfneXz6TNRnv1AWYSYoWWFf4edCio5MpBSvmDvtWsprcDFJ1hLFZ+sjEh7Yk8KgciOVi5UD0m8o0jHoPMLPFZNqM7zFf5gv7QG7/HNZJi5/Z61WGNpsHpbWctdeCXSjQNTjQZfo1ctBUOwEWk2ncavGJxQLfUhBTu1MQu3D2Bqfw8L0KcYbMXcoGeoDBHiND9IDJCoXRbiF98K/I6gmewavemsePtEejU4mQda5DPdFB8/81MYfEcSzRY/qqg3zxcr2DdIBfvildIDDeDc2I4UbPM4t7zCTweJW22jHzhHeg7z1oRtEVDMjLyk6AvSMpkrU8M3e/7x98kP/dW/rdrNEeX4p0iDYSqXZCMVROPLDoh5B5YelGAav73TEMHnQSwPBEKcMILaPQDKVy0YXb6ZktBuT7taJJCn0fMCMOHSAfbHcy+TqcOdQ3Waxq2+UkY8="

jobs:
    include:
        - stage: test
          script:
              - ./gradlew clean test 
        - stage: sonar
          script:
              - ./gradlew clean test
              - sonar-scanner
        - stage: deploy
          script:
              - ./gradlew clean jars
          deploy:
              provider: releases
              api_key:
                  secure: "j72+go5Rmpn8++wljg73/tCM2QwU5v83SI0RbQMXWMVfA9TEKksNZQViuo4+58un+Efdjj+rR8R3oY6OwFK57mcaFPqpc0lgpJSJ0KKzppsfIVvZRevxFs+zFqH89Er1Ul5kqq6aeMN84gehtyd3frrStDUsV33rdvqQ6u+GJn0dutjwruBMK+qC02lHKZS94ZqpQTW5QjfRdBa8h2O9c0lqNXKJNOhCl1GPJBOKzoWXwkBs4DN/Mw5sk7c1TdQu0b27WJ6cs/is6gSkELnFXM33YM5S3b6Y/EM181rJPpJaWfKntICTX96Giiytfl5qECxYq+4b/Yz8J8+kzGpSXv2FdZxzlVz5WFvsSAMVaz57s1zf7x4iCfx6MGOfv75HrsuFtum6rklJhT2iO7pqnDwl1hS8HFMueXbeUaTENTT4TWPYevlka4q1m9XXkPFp321uNLIF+6BtXMG2CEb53F7Ei47JRLoqVxSSnoxKQ3pQ/FrmG7wouIxCdGUWiYnKEZZ6Yxnn1hznTzmoEqc+bpgWq5ZKtIxGTyJEpvIAswvspnQHNVJyxKLGAsY5xsrav5kpeyZBIoIeuYDQOQ5biItPxiFM/BoNQlsTQFjmtp2k+UxEMONN7vwIKIYQQZBsz+8McxOUXkau2PZ5MNZwwH1AY9GrGqW4V3vdQ2/zE9A="
              file: dist/jkahypar-module-0.1.0.jar
              skip_cleanup: true
              on:
                  tags: true
